name: CD

on:
  push:
    branches: ["main"]

env:
  IMAGE_NAME: ghcr.io/chrmorod/project_weather_de_zoomcamp/streamlit:latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug structure
        run: |
          ls -la
          ls -la ./weather
          ls -la ./weather/app

      - name: Build Docker image
        run: |
          docker build \
            -t $IMAGE_NAME \
            -f ./weather/app/Dockerfile \
            ./weather

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME
